[theme]
base="dark"                # 'light' or 'dark'
primaryColor="#FF4B4B"     # 버튼 및 강조 텍스트 색상
backgroundColor="#0E1117"  # 앱 전체 배경
secondaryBackgroundColor="#262730"  # 위젯/컨테이너 배경
textColor="#FAFAFA"        # 본문 텍스트
font="sans serif"          # 'sans serif', 'serif', 'monospace'

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"    # 'minimal' or 'auto'
showErrorDetails = true

[browser]
gatherUsageStats = false
